In [ ]:
import numpy as np

arr = np.random.randint(1 ,100 , size =(10,5)) # sample - 10 , feature - 5

In [ ]:
arr.shape

(10, 5)

In [ ]:
b = arr.reshape(5,10)

b.shape
b.ndim
b

array([[63, 19, 88,  8,  9,  2, 61, 65, 45,  9],
       [73, 35, 26,  4,  8, 78, 84, 89, 57, 92],
       [32, 68, 28, 99, 41, 98, 97, 90, 19, 91],
       [90, 44, 91,  2, 44, 11, 84, 37, 27,  9],
       [ 9, 84, 54, 37, 55, 90, 46, 43, 86, 93]], dtype=int32)

In [ ]:
flatten = b.flatten()
print(flatten.ndim)
flatten

column_wise_flattening = np.ravel(b,order= 'C')

print(column_wise_flattening)

1
[63 19 88  8  9  2 61 65 45  9 73 35 26  4  8 78 84 89 57 92 32 68 28 99
 41 98 97 90 19 91 90 44 91  2 44 11 84 37 27  9  9 84 54 37 55 90 46 43
 86 93]


In [ ]:
a = np.random.randint(1 ,10 , size =(2,3))
b = np.random.randint(20 ,30 , size =(2,3))

[[5 4 2]
 [1 1 2]]
[[26 27 26]
 [24 25 23]]


### concatenate

In [ ]:
con_row = np.concatenate((a,b),axis=0) # row wise

print(con_row)

con_col = np.concatenate((a,b), axis = 1) # column wise

print(con_col)

[[ 5  4  2]
 [ 1  1  2]
 [26 27 26]
 [24 25 23]]
[[ 5  4  2 26 27 26]
 [ 1  1  2 24 25 23]]


In [ ]:
# error

# row wise concetanate korar shomoi column same thakbe
# col wise concat korar shomoi row ta same thakte hobe

x = np.random.randint(1 ,10 , size =(2,3))
y = np.random.randint(1 ,10 , size =(1,3))

r = np.concatenate((x,y),axis =0 )
r = np.concatenate((x,y),axis =1 )
print(r)


ValueError: all the input array dimensions except for the concatenation axis must match exactly, but along dimension 0, the array at index 0 has size 2 and the array at index 1 has size 1

In [ ]:
# transpose

mat = np.array([[10,20,30],
                [30,40,50]
               ])


transpose = mat.T

print(transpose)

[[10 30]
 [20 40]
 [30 50]]


In [ ]:
# array split

a = np.random.randint(1 ,10 , size =(10,))
print(a)
splitted_array = np.array_split(a,3)

print(splitted_array)

# split -> equal division
splitted_array = np.split(a,3)


[5 9 4 5 6 4 4 6 5 9]
[array([5, 9, 4, 5], dtype=int32), array([6, 4, 4], dtype=int32), array([6, 5, 9], dtype=int32)]


ValueError: array split does not result in an equal division

## arithmetic operator and mathematical functions

In [ ]:
# faster for vectorization

x = np.array([ 10 , 8 , 30 , 100 ])
y = np.array([ 2 , 3 ,4  ,5 ])

add = np.add(x,y)
print(add)

sub = x-y
print(sub)

mul = x*y
print(mul)

div = x/y
print(div)

remainder = x % y

print(remainder)


[ 12  11  34 105]
[ 8  5 26 95]
[ 20  24 120 500]
[ 5.          2.66666667  7.5        20.        ]
[0 2 2 0]


In [ ]:
# mathematical function

# trigonometry

# sin , cos , tan takes values in radian

sin_val = np.sin(x)
print(sin_val)

cos_val = np.cos(x)
print(cos_val)

deg_con = np.rad2deg(x)
print(deg_con)

# deg2rad


[-0.54402111  0.91294525 -0.98803162  0.74511316]
[-0.83907153  0.40808206  0.15425145 -0.66693806]
[ 572.95779513 1145.91559026 1718.87338539 2291.83118052]


In [ ]:
#log

x = np.array([ 10 , 8 , 16 , 100 ])
base_10_log_val = np.log10(x)
print(base_10_log_val)


two_diye_bhag = np.log2(x)
print(two_diye_bhag)

sqrt= np.sqrt(x)
print(sqrt)

[1.         0.90308999 1.20411998 2.        ]
[3.32192809 3.         4.         6.64385619]
[ 3.16227766  2.82842712  4.         10.        ]


In [ ]:
# different
s = np.sum(x)
print(s)

#prefix sum
cumul =np.cumulative_sum(x)
print(cumul)

134
[ 10  18  34 134]


## Logical Function

In [ ]:
# comparison - >,< , >= ,<= , == , !=

x = np.array([ 10 , 8 , 16 , 100 ])
y = np.array([ 2 , 3 ,16  ,5 ])

greater_than = x>y

print(greater_than)

equal = x==y

print(equal)

# all () -> shob true kina
# any() -> jekono ekta true ase kina

print(np.all(greater_than))

print(np.any(equal))


[ True  True False  True]
[False False  True False]
False
True


## Sorting

In [ ]:
#inplace
x = np.array([ 10 , 8 , 16 , 100 ])

z = x.copy()

print(z)

z.sort()

print(z)


[ 10   8  16 100]
[  8  10  16 100]


In [ ]:
# copy sorting
print(x)
sort_arr = np.sort(x)

print(sort_arr)

print(x)

[ 10   8  16 100]
[  8  10  16 100]
[ 10   8  16 100]


In [ ]:
# 2d array sorting
mat = np.array([[10,3,5],[8,4,9]])

# horizon axis = 1

hor_sort = np.sort(mat,axis=1)
print(hor_sort)

vert_sort = np.sort(mat,axis=0)
print(vert_sort)


[[ 3  5 10]
 [ 4  8  9]]
[[ 8  3  5]
 [10  4  9]]


## Searching

In [ ]:
print(x)

[ 10   8  16 100]


In [ ]:
# np.where( condition , x , y ) if true x , otherwise replace with y

index = np.where(x==8) # returns index
print(index)

arr = np.where(x>8,x,0) # returns array
print(arr)

(array([1]),)
[ 10   0  16 100]


In [ ]:
print(mat)

[[10  3  5]
 [ 8  4  9]]


In [ ]:
index = np.where(mat>8) # returns index
print(index)

arr = np.where(mat>8,mat,0) # returns array
print(arr)

(array([0, 1]), array([0, 2]))
[[10  0  0]
 [ 0  0  9]]


In [ ]:
x = np.array([ 10,100 , 8 , 16 , 100 ])

maximum_value_indx = np.argmax(x)
minimum_value_indx = np.argmin(x)

print(maximum_value_indx)
print(minimum_value_indx)

1
2


## counting in ndarray


In [ ]:
a = np.random.randint(1 ,100 , size =(100,))
print(a)

[63  9  1 21 25 41 99 58 97 19 30 77 35 68 18 16 21 46 49 60 49 34 82 76
 85 78  2 89 53 47 44 60 31 84 71 66 91 17 64 93 15 24 37 83 41 70 94  5
 56 17 15 30 69 97 42 20 31 52 94 29  2 55 35 10 63 69 72 95 39 63 34 23
 71 63 96 26 86 79 69 86 51 37 37 71 67  5 76 51 72 61 46 90 58 64 43 71
 86 67 21 29]


In [ ]:
value_great_than_60 = np.count_nonzero(a==97)
print(value_great_than_60)

2


In [ ]:
unique_value,count = np.unique(a,return_counts=True)

print(unique_value)
print(count)

[ 1  2  5  9 10 15 16 17 18 19 20 21 23 24 25 26 29 30 31 34 35 37 39 41
 42 43 44 46 47 49 51 52 53 55 56 58 60 61 63 64 66 67 68 69 70 71 72 76
 77 78 79 82 83 84 85 86 89 90 91 93 94 95 96 97 99]
[1 2 2 1 1 2 1 2 1 1 1 3 1 1 1 1 2 2 2 2 2 3 1 2 1 1 1 2 1 2 2 1 1 1 1 2 2
 1 4 2 1 2 1 3 1 4 2 2 1 1 1 1 1 1 1 3 1 1 1 1 2 1 1 2 1]


## statistical function

In [ ]:
#data load

data = np.genfromtxt('student_scores.csv' ,delimiter=',',skip_header=1)

print(data)


[[78. 85. 82.]
 [56. 67. 72.]
 [89. 92. 88.]
 [45. 52. 58.]
 [70. 75. 80.]
 [92. 90. 91.]
 [61. 60. 62.]
 [55. 57. 54.]
 [88. 89. 87.]
 [74. 70. 76.]
 [66. 69. 68.]
 [80. 82. 81.]
 [59. 64. 60.]
 [73. 78. 74.]
 [91. 93. 90.]
 [68. 71. 69.]
 [77. 79. 78.]
 [84. 86. 85.]
 [62. 63. 65.]
 [95. 97. 96.]]


In [ ]:
# statistics
math_marks = data[::,:1]

print(math_marks.T)

max_math_marks = np.max(math_marks)
print(max_math_marks)

min_math_marks = np.min(math_marks)
print(min_math_marks)

average_math_marks = np.mean(math_marks)
print(average_math_marks)

median_math_marks = np.median(math_marks)
print(median_math_marks)

# standard deviation

std_math_marks = np.std(math_marks)
print(std_math_marks)




[[78. 56. 89. 45. 70. 92. 61. 55. 88. 74. 66. 80. 59. 73. 91. 68. 77. 84.
  62. 95.]]
95.0
45.0
73.15
73.5
13.788672887555204


In [ ]:

study_hours = np.array([2, 4, 5, 7, 8])
exam_scores = np.array([65, 75, 78, 88, 92])

data = np.array([study_hours, exam_scores])

correlation = np.corrcoef(data)

print("Correlation Matrix:\n", correlation)


Correlation Matrix:
 [[1.         0.99859154]
 [0.99859154 1.        ]]


## linear algebra

In [ ]:
A = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

B = np.array([
    [7, 8],
    [9, 10],
    [11, 12]
])

# a er column and b er row same length hote hobe
dot_product = np.dot(A,B)
print(dot_product)


# trace
print(np.trace(B))


#

[[ 58  64]
 [139 154]]
17


In [ ]:
sq_mat = np.array([[1,2,3],
          [4,5,6],
          [7,8,9]
         ])

det_of_sq = np.linalg.det(sq_mat)

rank_sq = np.linalg.matrix_rank(sq_mat)

print(det_of_sq)

print(rank_sq)

6.66133814775094e-16
2


In [ ]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

print(np.dot(A,B))

[[19 22]
 [43 50]]
